---
- name: Ensure docker is installed correctly
  include_role:
    name: geerlingguy.docker
  when: ensure_docker_system
- name: Ensure docker python module is installed correctly
  include_role:
    name: geerlingguy.pip
  vars:
    pip_install_packages:
      - name: docker
  when: ensure_docker_python
- name: Deploy Web Services
  include_tasks: deploy-service.yml
  with_items: "{{ docker_web_services }}"
  loop_control:
    loop_var: service_definition
- name: Deploy Caddy
  include_role:
    name: deploy_caddy
