---
- name: Deploy Web Services
  include_tasks: deploy-service.yml
  with_items: "{{ docker_web_services }}"
  loop_control:
    loop_var: service_definition
- name: Deploy Caddy
  include_role:
    name: deploy_caddy
